// <auto-generated />
using System;
using CerebusBlazorUI.Utilities.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CerebusBlazorUI.Migrations
{
    [DbContext(typeof(CerebusContext))]
    [Migration("20260220030140_AddStates")]
    partial class AddStates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CerebusBlazorUI.Classes.Places.USState", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("USStates");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Abbreviation = "AL",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(4971),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Alabama",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(4974)
                        },
                        new
                        {
                            ID = 2,
                            Abbreviation = "AK",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5009),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Alaska",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5009)
                        },
                        new
                        {
                            ID = 3,
                            Abbreviation = "AZ",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5012),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Arizona",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5013)
                        },
                        new
                        {
                            ID = 4,
                            Abbreviation = "AR",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5015),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Arkansas",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5016)
                        },
                        new
                        {
                            ID = 5,
                            Abbreviation = "CA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5018),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "California",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5019)
                        },
                        new
                        {
                            ID = 6,
                            Abbreviation = "CO",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5021),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Colorado",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5021)
                        },
                        new
                        {
                            ID = 7,
                            Abbreviation = "CT",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5024),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Connecticut",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5024)
                        },
                        new
                        {
                            ID = 8,
                            Abbreviation = "DE",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5026),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Delaware",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5027)
                        },
                        new
                        {
                            ID = 9,
                            Abbreviation = "FL",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5029),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Florida",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5030)
                        },
                        new
                        {
                            ID = 10,
                            Abbreviation = "GA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5032),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Georgia",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5032)
                        },
                        new
                        {
                            ID = 11,
                            Abbreviation = "HI",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5034),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Hawaii",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5035)
                        },
                        new
                        {
                            ID = 12,
                            Abbreviation = "ID",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5037),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Idaho",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5038)
                        },
                        new
                        {
                            ID = 13,
                            Abbreviation = "IL",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5040),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Illinois",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5040)
                        },
                        new
                        {
                            ID = 14,
                            Abbreviation = "IN",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5058),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Indiana",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5059)
                        },
                        new
                        {
                            ID = 15,
                            Abbreviation = "IA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5061),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Iowa",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5062)
                        },
                        new
                        {
                            ID = 16,
                            Abbreviation = "KS",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5064),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Kansas",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5064)
                        },
                        new
                        {
                            ID = 17,
                            Abbreviation = "KY",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5066),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Kentucky",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5067)
                        },
                        new
                        {
                            ID = 18,
                            Abbreviation = "LA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5069),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Louisiana",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5069)
                        },
                        new
                        {
                            ID = 19,
                            Abbreviation = "ME",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5071),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Maine",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5072)
                        },
                        new
                        {
                            ID = 20,
                            Abbreviation = "MD",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5074),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Maryland",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5074)
                        },
                        new
                        {
                            ID = 21,
                            Abbreviation = "MA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5077),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Massachusetts",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5077)
                        },
                        new
                        {
                            ID = 22,
                            Abbreviation = "MI",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5079),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Michigan",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5079)
                        },
                        new
                        {
                            ID = 23,
                            Abbreviation = "MN",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5082),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Minnesota",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5082)
                        },
                        new
                        {
                            ID = 24,
                            Abbreviation = "MS",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5084),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Mississippi",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5085)
                        },
                        new
                        {
                            ID = 25,
                            Abbreviation = "MO",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5087),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Missouri",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5087)
                        },
                        new
                        {
                            ID = 26,
                            Abbreviation = "MT",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5103),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Montana",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5103)
                        },
                        new
                        {
                            ID = 27,
                            Abbreviation = "NE",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5106),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Nebraska",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5106)
                        },
                        new
                        {
                            ID = 28,
                            Abbreviation = "NV",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5109),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Nevada",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5109)
                        },
                        new
                        {
                            ID = 29,
                            Abbreviation = "NH",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5111),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "New Hampshire",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5112)
                        },
                        new
                        {
                            ID = 30,
                            Abbreviation = "NJ",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5114),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "New Jersey",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 507, DateTimeKind.Utc).AddTicks(5115)
                        },
                        new
                        {
                            ID = 31,
                            Abbreviation = "NM",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6059),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "New Mexico",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6060)
                        },
                        new
                        {
                            ID = 32,
                            Abbreviation = "NY",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6072),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "New York",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6072)
                        },
                        new
                        {
                            ID = 33,
                            Abbreviation = "NC",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6075),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "North Carolona",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6076)
                        },
                        new
                        {
                            ID = 34,
                            Abbreviation = "ND",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6078),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "North Dakota",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6079)
                        },
                        new
                        {
                            ID = 35,
                            Abbreviation = "OH",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6081),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Ohio",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6082)
                        },
                        new
                        {
                            ID = 36,
                            Abbreviation = "OK",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6085),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Oklahoma",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6085)
                        },
                        new
                        {
                            ID = 37,
                            Abbreviation = "OR",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6142),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Oregon",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6143)
                        },
                        new
                        {
                            ID = 38,
                            Abbreviation = "PA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6146),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Pennsylvania",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6146)
                        },
                        new
                        {
                            ID = 39,
                            Abbreviation = "RI",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6149),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Rhode Island",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6149)
                        },
                        new
                        {
                            ID = 40,
                            Abbreviation = "SC",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6152),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "South Carolina",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6153)
                        },
                        new
                        {
                            ID = 41,
                            Abbreviation = "SD",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6156),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "South Dakota",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6157)
                        },
                        new
                        {
                            ID = 42,
                            Abbreviation = "TN",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6159),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Tennessee",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6160)
                        },
                        new
                        {
                            ID = 43,
                            Abbreviation = "TX",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6162),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Texas",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6163)
                        },
                        new
                        {
                            ID = 44,
                            Abbreviation = "UT",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6165),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Utah",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6166)
                        },
                        new
                        {
                            ID = 45,
                            Abbreviation = "VT",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6168),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Vermont",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6168)
                        },
                        new
                        {
                            ID = 46,
                            Abbreviation = "VA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6171),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Virginia",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6171)
                        },
                        new
                        {
                            ID = 47,
                            Abbreviation = "WA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6174),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Washington",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6174)
                        },
                        new
                        {
                            ID = 48,
                            Abbreviation = "WV",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6177),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "West Virginia",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6177)
                        },
                        new
                        {
                            ID = 49,
                            Abbreviation = "WI",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6180),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Wisconsin",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6180)
                        },
                        new
                        {
                            ID = 50,
                            Abbreviation = "WY",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6183),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Wyoming",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6183)
                        },
                        new
                        {
                            ID = 51,
                            Abbreviation = "DC",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6186),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "District of Columbia",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6186)
                        },
                        new
                        {
                            ID = 52,
                            Abbreviation = "PR",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6189),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Puerto Rico",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 20, 3, 1, 39, 512, DateTimeKind.Utc).AddTicks(6189)
                        });
                });

            modelBuilder.Entity("CerebusBlazorUI.Classes.User.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MiddleNameOrInitial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            City = "New York",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Bob.Reed@Cerebus.fake",
                            FirstName = "Bob",
                            HireDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Reed",
                            MiddleNameOrInitial = "L",
                            Password = "AHRoHFuSN14WPgLpdm/5sGdh0GjmPJegCVSyzTpJIqYc3mQJTvrDwgqqiyWau5qBkQ==",
                            PhoneNumber = "646-555-3047",
                            State = "32",
                            StreetAddress = "814 Geraldine Lane",
                            Title = "CEO",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Bob.Reed",
                            ZipCode = "10011"
                        },
                        new
                        {
                            ID = 2,
                            City = "Buffalo",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Latoya.Carter@Cerebus.fake",
                            FirstName = "Latoya",
                            HireDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Carter",
                            MiddleNameOrInitial = "N",
                            Password = "APHxbsLp4xTnlOvRw17p6nM0ylvuKtiNUbJc9AYiSUpbR2Lttj7aa9CHkubk8EShLw==",
                            PhoneNumber = "716-555-3630",
                            State = "32",
                            StreetAddress = "2034 Jarvis Street",
                            Title = "HR Generalist",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Latoya.Carter",
                            ZipCode = "14222"
                        },
                        new
                        {
                            ID = 3,
                            City = "Cambridge",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2021, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Joshua.Boyer@Cerebus.fake",
                            FirstName = "Joshua",
                            HireDate = new DateTime(2021, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Boyer",
                            MiddleNameOrInitial = "O",
                            Password = "ADYrcpQROhC+kFR7VsqwvhMcs87KKQCvRghg0rCacKryRet+DVSihvrmgyye+zkPLQ==",
                            PhoneNumber = "508-555-2320",
                            State = "21",
                            StreetAddress = "3821 Randolph Street",
                            Title = "IT Director",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2021, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Joshua.Boyer",
                            ZipCode = "02141"
                        },
                        new
                        {
                            ID = 4,
                            City = "New York",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Sandy.William@Cerebus.fake",
                            FirstName = "Sandy",
                            HireDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "William",
                            MiddleNameOrInitial = "E",
                            Password = "AKTusS+Q0O2mAJYM32BYzeF93P0FnxgMbq/R1nloiGm5DBS+EAaR5SvZk1nIbe2+OA==",
                            PhoneNumber = "212-555-3480",
                            State = "32",
                            StreetAddress = "35 Godfrey Road",
                            Title = "Systems Administrator",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Sandy.William",
                            ZipCode = "10022"
                        },
                        new
                        {
                            ID = 5,
                            City = "Hartford",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Christopher.Cross@Cerebus.fake",
                            FirstName = "Christopher",
                            HireDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Cross",
                            MiddleNameOrInitial = "U",
                            Password = "APZozU0Y2NQsegcAtt8bAArDsnxmfqlrvV3gHIab23vfA3f/7NwIPGnPxgC/kHPONA==",
                            PhoneNumber = "860-555-0200",
                            State = "7",
                            StreetAddress = "459 Hart Street",
                            Title = "IT Technician",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Christopher.Cross",
                            ZipCode = "06103"
                        },
                        new
                        {
                            ID = 6,
                            City = "Albany",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Trevor.Ryan@Cerebus.fake",
                            FirstName = "Trevor",
                            HireDate = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Ryan",
                            MiddleNameOrInitial = "M",
                            Password = "AGqDayCJRl1HE2fDbeAmBguFhrD4eiCBn+x665lR/P8Wl2JFezl982/mdgOhGgONTw==",
                            PhoneNumber = "518-555-2034",
                            State = "32",
                            StreetAddress = "3564 Hardesty Street",
                            Title = "IT Technician",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Trevor.Ryan",
                            ZipCode = "12207"
                        },
                        new
                        {
                            ID = 7,
                            City = "Andover",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Arlene.Dawson@Cerebus.fake",
                            FirstName = "Arlene",
                            HireDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Dawson",
                            MiddleNameOrInitial = "R",
                            Password = "AP68XrJHalXtdwcFwNFNhu23g/12Jg1tMtaMhbNZuIcwex5OTf11fHA1Im/MMLgJYQ==",
                            PhoneNumber = "207-555-2113",
                            State = "19",
                            StreetAddress = "262 Victoria Court",
                            Title = "Software Developer",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Arlene.Dawson",
                            ZipCode = "04216"
                        },
                        new
                        {
                            ID = 8,
                            City = "Clarion",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Anna.Hartman@Cerebus.fake",
                            FirstName = "Anna",
                            HireDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Hartman",
                            MiddleNameOrInitial = "A",
                            Password = "AEpSHTogjKMFhZ2e8XkzJCgosUWq9wPciYf98eO/xl+1CWtClDvsXVy9RbdKSEaKpQ==",
                            PhoneNumber = "814-555-1968",
                            State = "38",
                            StreetAddress = "2797 Coal Street",
                            Title = "Customer Service Manager",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Anna.Hartman",
                            ZipCode = "16214"
                        },
                        new
                        {
                            ID = 9,
                            City = "Millington",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Janette.James@Cerebus.fake",
                            FirstName = "Janette",
                            HireDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "James",
                            MiddleNameOrInitial = "W",
                            Password = "AL+xGbePile7fZHqCJNCbsX6nYktE+npt6DvKt+w5EoAO4Ttc0UE04YMmQTutRYlbA==",
                            PhoneNumber = "908-555-4192",
                            State = "30",
                            StreetAddress = "1198 Hedge Street",
                            Title = "Customer Service Representative",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Janette.James",
                            ZipCode = "07946"
                        },
                        new
                        {
                            ID = 10,
                            City = "Syracuse",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Van.Harmon@Cerebus.fake",
                            FirstName = "Van",
                            HireDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Harmon",
                            MiddleNameOrInitial = "T",
                            Password = "AImU1FPqP/A4NPLkhoKeDvyZY6Xq4/cCjJMgw1LUv3LhHOSkhMRgrJNnLCLeMXWV8w==",
                            PhoneNumber = "315-555-7346",
                            State = "32",
                            StreetAddress = "1698 Saint Marys Avenue",
                            Title = "Customer Service Representative",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Van.Harmon",
                            ZipCode = "13221"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
