// <auto-generated />
using System;
using CerebusBlazorUI.Utilities.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CerebusBlazorUI.Migrations
{
    [DbContext(typeof(CerebusContext))]
    [Migration("20260224211020_AddUserRoleTable")]
    partial class AddUserRoleTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CerebusBlazorUI.Classes.Places.USState", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("USStates");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Abbreviation = "AL",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 348, DateTimeKind.Utc).AddTicks(9917),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Alabama",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 348, DateTimeKind.Utc).AddTicks(9920)
                        },
                        new
                        {
                            ID = 2,
                            Abbreviation = "AK",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 348, DateTimeKind.Utc).AddTicks(9925),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Alaska",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 348, DateTimeKind.Utc).AddTicks(9926)
                        },
                        new
                        {
                            ID = 3,
                            Abbreviation = "AZ",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 348, DateTimeKind.Utc).AddTicks(9928),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Arizona",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 348, DateTimeKind.Utc).AddTicks(9929)
                        },
                        new
                        {
                            ID = 4,
                            Abbreviation = "AR",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 348, DateTimeKind.Utc).AddTicks(9931),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Arkansas",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 348, DateTimeKind.Utc).AddTicks(9932)
                        },
                        new
                        {
                            ID = 5,
                            Abbreviation = "CA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 348, DateTimeKind.Utc).AddTicks(9962),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "California",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 348, DateTimeKind.Utc).AddTicks(9962)
                        },
                        new
                        {
                            ID = 6,
                            Abbreviation = "CO",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 348, DateTimeKind.Utc).AddTicks(9965),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Colorado",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 348, DateTimeKind.Utc).AddTicks(9965)
                        },
                        new
                        {
                            ID = 7,
                            Abbreviation = "CT",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 348, DateTimeKind.Utc).AddTicks(9968),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Connecticut",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 348, DateTimeKind.Utc).AddTicks(9968)
                        },
                        new
                        {
                            ID = 8,
                            Abbreviation = "DE",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 348, DateTimeKind.Utc).AddTicks(9971),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Delaware",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 348, DateTimeKind.Utc).AddTicks(9971)
                        },
                        new
                        {
                            ID = 9,
                            Abbreviation = "FL",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 348, DateTimeKind.Utc).AddTicks(9974),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Florida",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 348, DateTimeKind.Utc).AddTicks(9974)
                        },
                        new
                        {
                            ID = 10,
                            Abbreviation = "GA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(8),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Georgia",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(9)
                        },
                        new
                        {
                            ID = 11,
                            Abbreviation = "HI",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(12),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Hawaii",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(12)
                        },
                        new
                        {
                            ID = 12,
                            Abbreviation = "ID",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(15),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Idaho",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(15)
                        },
                        new
                        {
                            ID = 13,
                            Abbreviation = "IL",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(17),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Illinois",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(18)
                        },
                        new
                        {
                            ID = 14,
                            Abbreviation = "IN",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(21),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Indiana",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(21)
                        },
                        new
                        {
                            ID = 15,
                            Abbreviation = "IA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(24),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Iowa",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(24)
                        },
                        new
                        {
                            ID = 16,
                            Abbreviation = "KS",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(27),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Kansas",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(27)
                        },
                        new
                        {
                            ID = 17,
                            Abbreviation = "KY",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(30),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Kentucky",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(30)
                        },
                        new
                        {
                            ID = 18,
                            Abbreviation = "LA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(33),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Louisiana",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(33)
                        },
                        new
                        {
                            ID = 19,
                            Abbreviation = "ME",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(35),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Maine",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(36)
                        },
                        new
                        {
                            ID = 20,
                            Abbreviation = "MD",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(38),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Maryland",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(39)
                        },
                        new
                        {
                            ID = 21,
                            Abbreviation = "MA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(41),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Massachusetts",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(42)
                        },
                        new
                        {
                            ID = 22,
                            Abbreviation = "MI",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(58),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Michigan",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(58)
                        },
                        new
                        {
                            ID = 23,
                            Abbreviation = "MN",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(61),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Minnesota",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(61)
                        },
                        new
                        {
                            ID = 24,
                            Abbreviation = "MS",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(64),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Mississippi",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(64)
                        },
                        new
                        {
                            ID = 25,
                            Abbreviation = "MO",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(67),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Missouri",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(67)
                        },
                        new
                        {
                            ID = 26,
                            Abbreviation = "MT",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(70),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Montana",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(70)
                        },
                        new
                        {
                            ID = 27,
                            Abbreviation = "NE",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(73),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Nebraska",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(73)
                        },
                        new
                        {
                            ID = 28,
                            Abbreviation = "NV",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(76),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Nevada",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(76)
                        },
                        new
                        {
                            ID = 29,
                            Abbreviation = "NH",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(79),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "New Hampshire",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(79)
                        },
                        new
                        {
                            ID = 30,
                            Abbreviation = "NJ",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(81),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "New Jersey",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(82)
                        },
                        new
                        {
                            ID = 31,
                            Abbreviation = "NM",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(84),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "New Mexico",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(85)
                        },
                        new
                        {
                            ID = 32,
                            Abbreviation = "NY",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(87),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "New York",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(88)
                        },
                        new
                        {
                            ID = 33,
                            Abbreviation = "NC",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(90),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "North Carolona",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(90)
                        },
                        new
                        {
                            ID = 34,
                            Abbreviation = "ND",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(106),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "North Dakota",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(107)
                        },
                        new
                        {
                            ID = 35,
                            Abbreviation = "OH",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(109),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Ohio",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(110)
                        },
                        new
                        {
                            ID = 36,
                            Abbreviation = "OK",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(112),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Oklahoma",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(113)
                        },
                        new
                        {
                            ID = 37,
                            Abbreviation = "OR",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(115),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Oregon",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(116)
                        },
                        new
                        {
                            ID = 38,
                            Abbreviation = "PA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(118),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Pennsylvania",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(118)
                        },
                        new
                        {
                            ID = 39,
                            Abbreviation = "RI",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(120),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Rhode Island",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(121)
                        },
                        new
                        {
                            ID = 40,
                            Abbreviation = "SC",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(123),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "South Carolina",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(124)
                        },
                        new
                        {
                            ID = 41,
                            Abbreviation = "SD",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(126),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "South Dakota",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(127)
                        },
                        new
                        {
                            ID = 42,
                            Abbreviation = "TN",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(129),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Tennessee",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(130)
                        },
                        new
                        {
                            ID = 43,
                            Abbreviation = "TX",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(132),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Texas",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(133)
                        },
                        new
                        {
                            ID = 44,
                            Abbreviation = "UT",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(135),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Utah",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(135)
                        },
                        new
                        {
                            ID = 45,
                            Abbreviation = "VT",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(138),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Vermont",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(138)
                        },
                        new
                        {
                            ID = 46,
                            Abbreviation = "VA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(140),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Virginia",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(141)
                        },
                        new
                        {
                            ID = 47,
                            Abbreviation = "WA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(143),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Washington",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(144)
                        },
                        new
                        {
                            ID = 48,
                            Abbreviation = "WV",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(146),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "West Virginia",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(147)
                        },
                        new
                        {
                            ID = 49,
                            Abbreviation = "WI",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(149),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Wisconsin",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(149)
                        },
                        new
                        {
                            ID = 50,
                            Abbreviation = "WY",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(151),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Wyoming",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(152)
                        },
                        new
                        {
                            ID = 51,
                            Abbreviation = "DC",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(154),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "District of Columbia",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(155)
                        },
                        new
                        {
                            ID = 52,
                            Abbreviation = "PR",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(157),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Puerto Rico",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 21, 10, 19, 349, DateTimeKind.Utc).AddTicks(157)
                        });
                });

            modelBuilder.Entity("CerebusBlazorUI.Classes.User.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MiddleNameOrInitial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            City = "New York",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Bob.Reed@Cerebus.fake",
                            FirstName = "Bob",
                            HireDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Reed",
                            MiddleNameOrInitial = "L",
                            Password = "AM25rfn498HhSwjEwCgpnnXZGfmvMbdmp1R/gdZrpMMrIidHDSZ5Y7XwMJtR5g6SKg==",
                            PhoneNumber = "646-555-3047",
                            State = "32",
                            StreetAddress = "814 Geraldine Lane",
                            Title = "CEO",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Bob.Reed",
                            ZipCode = "10011"
                        },
                        new
                        {
                            ID = 2,
                            City = "Buffalo",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Latoya.Carter@Cerebus.fake",
                            FirstName = "Latoya",
                            HireDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Carter",
                            MiddleNameOrInitial = "N",
                            Password = "AG07dIPyxsLdWzuyimzTiDgRQuKNjVYhrI7h4gOEF44css3vDE+gtRNBFItDeH7x1w==",
                            PhoneNumber = "716-555-3630",
                            State = "32",
                            StreetAddress = "2034 Jarvis Street",
                            Title = "HR Generalist",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Latoya.Carter",
                            ZipCode = "14222"
                        },
                        new
                        {
                            ID = 3,
                            City = "Cambridge",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2021, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Joshua.Boyer@Cerebus.fake",
                            FirstName = "Joshua",
                            HireDate = new DateTime(2021, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Boyer",
                            MiddleNameOrInitial = "O",
                            Password = "AEkBh5o8HQlvRLo8Qau5U6Rx9fz980ifzZyLjsJ1Hv4DAI8rp193d9tofiLHZdEHEg==",
                            PhoneNumber = "508-555-2320",
                            State = "21",
                            StreetAddress = "3821 Randolph Street",
                            Title = "IT Director",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2021, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Joshua.Boyer",
                            ZipCode = "02141"
                        },
                        new
                        {
                            ID = 4,
                            City = "New York",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Sandy.William@Cerebus.fake",
                            FirstName = "Sandy",
                            HireDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "William",
                            MiddleNameOrInitial = "E",
                            Password = "AHwSwAVpdIw/iyomRgpYKeA0M39/sJtJhWlEp3BroWjV8tS4oC4WVEAHMeLUF1ABsQ==",
                            PhoneNumber = "212-555-3480",
                            State = "32",
                            StreetAddress = "35 Godfrey Road",
                            Title = "Systems Administrator",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Sandy.William",
                            ZipCode = "10022"
                        },
                        new
                        {
                            ID = 5,
                            City = "Hartford",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Christopher.Cross@Cerebus.fake",
                            FirstName = "Christopher",
                            HireDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Cross",
                            MiddleNameOrInitial = "U",
                            Password = "AKBsiXg5u9k+egRFlltrlsCpwQOFMHclovvhfe1m3aYkURCLuXBD20qhseIywSoqCA==",
                            PhoneNumber = "860-555-0200",
                            State = "7",
                            StreetAddress = "459 Hart Street",
                            Title = "IT Technician",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Christopher.Cross",
                            ZipCode = "06103"
                        },
                        new
                        {
                            ID = 6,
                            City = "Albany",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Trevor.Ryan@Cerebus.fake",
                            FirstName = "Trevor",
                            HireDate = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Ryan",
                            MiddleNameOrInitial = "M",
                            Password = "AAMClsiMmi7Owm+pD2iD8ZZkXpv9FvcNd16jgzuUuzshwwc2EKCjEbZ4wJhEQ8AFLQ==",
                            PhoneNumber = "518-555-2034",
                            State = "32",
                            StreetAddress = "3564 Hardesty Street",
                            Title = "IT Technician",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Trevor.Ryan",
                            ZipCode = "12207"
                        },
                        new
                        {
                            ID = 7,
                            City = "Andover",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Arlene.Dawson@Cerebus.fake",
                            FirstName = "Arlene",
                            HireDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Dawson",
                            MiddleNameOrInitial = "R",
                            Password = "AFbewvagJch2bMDVEsA+f43ZGGOTHd2ThZUbyMNHzfmahpvN16eY09oDfi0OsLmrZA==",
                            PhoneNumber = "207-555-2113",
                            State = "19",
                            StreetAddress = "262 Victoria Court",
                            Title = "Software Developer",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Arlene.Dawson",
                            ZipCode = "04216"
                        },
                        new
                        {
                            ID = 8,
                            City = "Clarion",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Anna.Hartman@Cerebus.fake",
                            FirstName = "Anna",
                            HireDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Hartman",
                            MiddleNameOrInitial = "A",
                            Password = "AD0BjkmEDliraWhIW6yrv8nYb1YafYy2f16K9C6YDioa9XIds/hQ5obJNWiZIA00hA==",
                            PhoneNumber = "814-555-1968",
                            State = "38",
                            StreetAddress = "2797 Coal Street",
                            Title = "Customer Service Manager",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Anna.Hartman",
                            ZipCode = "16214"
                        },
                        new
                        {
                            ID = 9,
                            City = "Millington",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Janette.James@Cerebus.fake",
                            FirstName = "Janette",
                            HireDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "James",
                            MiddleNameOrInitial = "W",
                            Password = "ACXX7jLhQoMmT1zqz7a8RCNEjetvJzw2fEN4Hp4uPtKCkqz9o8czoBe2Uxq0ZRfYSQ==",
                            PhoneNumber = "908-555-4192",
                            State = "30",
                            StreetAddress = "1198 Hedge Street",
                            Title = "Customer Service Representative",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Janette.James",
                            ZipCode = "07946"
                        },
                        new
                        {
                            ID = 10,
                            City = "Syracuse",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Van.Harmon@Cerebus.fake",
                            FirstName = "Van",
                            HireDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Harmon",
                            MiddleNameOrInitial = "T",
                            Password = "APsU4dqJry6dGFirAR4LnkLfrx/LiKFfcZmLvtRYPnpjbt0ClkLrHSPvZ2jObIFxHA==",
                            PhoneNumber = "315-555-7346",
                            State = "32",
                            StreetAddress = "1698 Saint Marys Avenue",
                            Title = "Customer Service Representative",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Van.Harmon",
                            ZipCode = "13221"
                        });
                });

            modelBuilder.Entity("CerebusBlazorUI.Classes.User.UserRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsManager")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
