// <auto-generated />
using System;
using CerebusBlazorUI.Utilities.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CerebusBlazorUI.Migrations
{
    [DbContext(typeof(CerebusContext))]
    [Migration("20260224201559_AddStateForeignKeyToUser")]
    partial class AddStateForeignKeyToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CerebusBlazorUI.Classes.Places.USState", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("USStates");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Abbreviation = "AL",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8109),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Alabama",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8112)
                        },
                        new
                        {
                            ID = 2,
                            Abbreviation = "AK",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8118),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Alaska",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8119)
                        },
                        new
                        {
                            ID = 3,
                            Abbreviation = "AZ",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8149),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Arizona",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8150)
                        },
                        new
                        {
                            ID = 4,
                            Abbreviation = "AR",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8154),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Arkansas",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8154)
                        },
                        new
                        {
                            ID = 5,
                            Abbreviation = "CA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8157),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "California",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8158)
                        },
                        new
                        {
                            ID = 6,
                            Abbreviation = "CO",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8160),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Colorado",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8161)
                        },
                        new
                        {
                            ID = 7,
                            Abbreviation = "CT",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8164),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Connecticut",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8164)
                        },
                        new
                        {
                            ID = 8,
                            Abbreviation = "DE",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8167),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Delaware",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8168)
                        },
                        new
                        {
                            ID = 9,
                            Abbreviation = "FL",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8170),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Florida",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8171)
                        },
                        new
                        {
                            ID = 10,
                            Abbreviation = "GA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8174),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Georgia",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8174)
                        },
                        new
                        {
                            ID = 11,
                            Abbreviation = "HI",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8177),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Hawaii",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8177)
                        },
                        new
                        {
                            ID = 12,
                            Abbreviation = "ID",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8180),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Idaho",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8181)
                        },
                        new
                        {
                            ID = 13,
                            Abbreviation = "IL",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8183),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Illinois",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8183)
                        },
                        new
                        {
                            ID = 14,
                            Abbreviation = "IN",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8186),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Indiana",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8186)
                        },
                        new
                        {
                            ID = 15,
                            Abbreviation = "IA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8209),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Iowa",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8210)
                        },
                        new
                        {
                            ID = 16,
                            Abbreviation = "KS",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8213),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Kansas",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8214)
                        },
                        new
                        {
                            ID = 17,
                            Abbreviation = "KY",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8216),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Kentucky",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8217)
                        },
                        new
                        {
                            ID = 18,
                            Abbreviation = "LA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8219),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Louisiana",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8220)
                        },
                        new
                        {
                            ID = 19,
                            Abbreviation = "ME",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8222),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Maine",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8223)
                        },
                        new
                        {
                            ID = 20,
                            Abbreviation = "MD",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8225),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Maryland",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8226)
                        },
                        new
                        {
                            ID = 21,
                            Abbreviation = "MA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8229),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Massachusetts",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8229)
                        },
                        new
                        {
                            ID = 22,
                            Abbreviation = "MI",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8232),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Michigan",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8232)
                        },
                        new
                        {
                            ID = 23,
                            Abbreviation = "MN",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8235),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Minnesota",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8236)
                        },
                        new
                        {
                            ID = 24,
                            Abbreviation = "MS",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8238),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Mississippi",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8239)
                        },
                        new
                        {
                            ID = 25,
                            Abbreviation = "MO",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8242),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Missouri",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8242)
                        },
                        new
                        {
                            ID = 26,
                            Abbreviation = "MT",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8245),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Montana",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8245)
                        },
                        new
                        {
                            ID = 27,
                            Abbreviation = "NE",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8267),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Nebraska",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8267)
                        },
                        new
                        {
                            ID = 28,
                            Abbreviation = "NV",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8270),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Nevada",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8270)
                        },
                        new
                        {
                            ID = 29,
                            Abbreviation = "NH",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8273),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "New Hampshire",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8273)
                        },
                        new
                        {
                            ID = 30,
                            Abbreviation = "NJ",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8276),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "New Jersey",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8276)
                        },
                        new
                        {
                            ID = 31,
                            Abbreviation = "NM",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8279),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "New Mexico",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8279)
                        },
                        new
                        {
                            ID = 32,
                            Abbreviation = "NY",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8282),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "New York",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8282)
                        },
                        new
                        {
                            ID = 33,
                            Abbreviation = "NC",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8285),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "North Carolona",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8285)
                        },
                        new
                        {
                            ID = 34,
                            Abbreviation = "ND",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8288),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "North Dakota",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8289)
                        },
                        new
                        {
                            ID = 35,
                            Abbreviation = "OH",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8291),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Ohio",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8291)
                        },
                        new
                        {
                            ID = 36,
                            Abbreviation = "OK",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8294),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Oklahoma",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8295)
                        },
                        new
                        {
                            ID = 37,
                            Abbreviation = "OR",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8297),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Oregon",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8298)
                        },
                        new
                        {
                            ID = 38,
                            Abbreviation = "PA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8315),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Pennsylvania",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8316)
                        },
                        new
                        {
                            ID = 39,
                            Abbreviation = "RI",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8319),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Rhode Island",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8319)
                        },
                        new
                        {
                            ID = 40,
                            Abbreviation = "SC",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8322),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "South Carolina",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8323)
                        },
                        new
                        {
                            ID = 41,
                            Abbreviation = "SD",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8326),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "South Dakota",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8326)
                        },
                        new
                        {
                            ID = 42,
                            Abbreviation = "TN",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8329),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Tennessee",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8329)
                        },
                        new
                        {
                            ID = 43,
                            Abbreviation = "TX",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8332),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Texas",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8332)
                        },
                        new
                        {
                            ID = 44,
                            Abbreviation = "UT",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8363),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Utah",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8364)
                        },
                        new
                        {
                            ID = 45,
                            Abbreviation = "VT",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8367),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Vermont",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8367)
                        },
                        new
                        {
                            ID = 46,
                            Abbreviation = "VA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8370),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Virginia",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8370)
                        },
                        new
                        {
                            ID = 47,
                            Abbreviation = "WA",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8373),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Washington",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8373)
                        },
                        new
                        {
                            ID = 48,
                            Abbreviation = "WV",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8376),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "West Virginia",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8377)
                        },
                        new
                        {
                            ID = 49,
                            Abbreviation = "WI",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8379),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Wisconsin",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8380)
                        },
                        new
                        {
                            ID = 50,
                            Abbreviation = "WY",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8382),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Wyoming",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8383)
                        },
                        new
                        {
                            ID = 51,
                            Abbreviation = "DC",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8385),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "District of Columbia",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8386)
                        },
                        new
                        {
                            ID = 52,
                            Abbreviation = "PR",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8389),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Puerto Rico",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2026, 2, 24, 20, 15, 58, 310, DateTimeKind.Utc).AddTicks(8389)
                        });
                });

            modelBuilder.Entity("CerebusBlazorUI.Classes.User.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MiddleNameOrInitial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("USStateID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ID");

                    b.HasIndex("USStateID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            City = "New York",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Bob.Reed@Cerebus.fake",
                            FirstName = "Bob",
                            HireDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Reed",
                            MiddleNameOrInitial = "L",
                            Password = "AKH+3tDerSVGjhVbP8SZH5sjV0322crmA7kVSyO8R/27jVIiwvpfdcN+0MTD8TsBmw==",
                            PhoneNumber = "646-555-3047",
                            State = "32",
                            StreetAddress = "814 Geraldine Lane",
                            Title = "CEO",
                            USStateID = 0,
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Bob.Reed",
                            ZipCode = "10011"
                        },
                        new
                        {
                            ID = 2,
                            City = "Buffalo",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Latoya.Carter@Cerebus.fake",
                            FirstName = "Latoya",
                            HireDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Carter",
                            MiddleNameOrInitial = "N",
                            Password = "AJXWpzUAuRZAmtyZ9oUEGQ2NO/BZHSSlKBqeVZwkMtSBru64qVmIF17+hb4n3r7hhA==",
                            PhoneNumber = "716-555-3630",
                            State = "32",
                            StreetAddress = "2034 Jarvis Street",
                            Title = "HR Generalist",
                            USStateID = 0,
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Latoya.Carter",
                            ZipCode = "14222"
                        },
                        new
                        {
                            ID = 3,
                            City = "Cambridge",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2021, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Joshua.Boyer@Cerebus.fake",
                            FirstName = "Joshua",
                            HireDate = new DateTime(2021, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Boyer",
                            MiddleNameOrInitial = "O",
                            Password = "AKIXV3/R+gQXqTfwmIHVuID2q2l/6V2ld4RYXDikqZLkknwSJtGVd5SoKQWi5FnzBA==",
                            PhoneNumber = "508-555-2320",
                            State = "21",
                            StreetAddress = "3821 Randolph Street",
                            Title = "IT Director",
                            USStateID = 0,
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2021, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Joshua.Boyer",
                            ZipCode = "02141"
                        },
                        new
                        {
                            ID = 4,
                            City = "New York",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Sandy.William@Cerebus.fake",
                            FirstName = "Sandy",
                            HireDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "William",
                            MiddleNameOrInitial = "E",
                            Password = "AAdp4SWloi37g1kbKmOOI+HTZp2VA34qhBYENzryNAWywuvmy4mr7SMBaxkAL8OdTA==",
                            PhoneNumber = "212-555-3480",
                            State = "32",
                            StreetAddress = "35 Godfrey Road",
                            Title = "Systems Administrator",
                            USStateID = 0,
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Sandy.William",
                            ZipCode = "10022"
                        },
                        new
                        {
                            ID = 5,
                            City = "Hartford",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Christopher.Cross@Cerebus.fake",
                            FirstName = "Christopher",
                            HireDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Cross",
                            MiddleNameOrInitial = "U",
                            Password = "AGrlV6mXKpkETmyuFoM9WGtvjU7B1LHumC9T8LF+2++p+LjL0fyFI6rYNlahcIkSUw==",
                            PhoneNumber = "860-555-0200",
                            State = "7",
                            StreetAddress = "459 Hart Street",
                            Title = "IT Technician",
                            USStateID = 0,
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Christopher.Cross",
                            ZipCode = "06103"
                        },
                        new
                        {
                            ID = 6,
                            City = "Albany",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Trevor.Ryan@Cerebus.fake",
                            FirstName = "Trevor",
                            HireDate = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Ryan",
                            MiddleNameOrInitial = "M",
                            Password = "ACPHQhZpTpqVLD2x9wt8yOxCn+MLvSYMkTbSCClUf/ZWWuYr0syzC2Uj6cnMUxelCw==",
                            PhoneNumber = "518-555-2034",
                            State = "32",
                            StreetAddress = "3564 Hardesty Street",
                            Title = "IT Technician",
                            USStateID = 0,
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Trevor.Ryan",
                            ZipCode = "12207"
                        },
                        new
                        {
                            ID = 7,
                            City = "Andover",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Arlene.Dawson@Cerebus.fake",
                            FirstName = "Arlene",
                            HireDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Dawson",
                            MiddleNameOrInitial = "R",
                            Password = "AK0WsFSQKaspM+quZP+aHsg7+KB5WeQgZqvB2tuK+X9VDqB5KaH9xsJMub1HdD2t4g==",
                            PhoneNumber = "207-555-2113",
                            State = "19",
                            StreetAddress = "262 Victoria Court",
                            Title = "Software Developer",
                            USStateID = 0,
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Arlene.Dawson",
                            ZipCode = "04216"
                        },
                        new
                        {
                            ID = 8,
                            City = "Clarion",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Anna.Hartman@Cerebus.fake",
                            FirstName = "Anna",
                            HireDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Hartman",
                            MiddleNameOrInitial = "A",
                            Password = "AGI6/IWblm10FIeUIsmi6omtgxDnHLLbXKXuSwbHX5cXTzgDhMYXCQyQQj+LAALzJg==",
                            PhoneNumber = "814-555-1968",
                            State = "38",
                            StreetAddress = "2797 Coal Street",
                            Title = "Customer Service Manager",
                            USStateID = 0,
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Anna.Hartman",
                            ZipCode = "16214"
                        },
                        new
                        {
                            ID = 9,
                            City = "Millington",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Janette.James@Cerebus.fake",
                            FirstName = "Janette",
                            HireDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "James",
                            MiddleNameOrInitial = "W",
                            Password = "APD0ViYfX3fMQBekx2BefgBwoagAlTWdkCflOHkB5IiU/fTIPX9PsZbLUQmEXMScIw==",
                            PhoneNumber = "908-555-4192",
                            State = "30",
                            StreetAddress = "1198 Hedge Street",
                            Title = "Customer Service Representative",
                            USStateID = 0,
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Janette.James",
                            ZipCode = "07946"
                        },
                        new
                        {
                            ID = 10,
                            City = "Syracuse",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Van.Harmon@Cerebus.fake",
                            FirstName = "Van",
                            HireDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Harmon",
                            MiddleNameOrInitial = "T",
                            Password = "ANLNjglkmVgYNj/LiLTbw+RPDO8B87Gkz8tMM46ae25TlMPEvocQ4NHweu3TT6/EhQ==",
                            PhoneNumber = "315-555-7346",
                            State = "32",
                            StreetAddress = "1698 Saint Marys Avenue",
                            Title = "Customer Service Representative",
                            USStateID = 0,
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Van.Harmon",
                            ZipCode = "13221"
                        });
                });

            modelBuilder.Entity("CerebusBlazorUI.Classes.User.User", b =>
                {
                    b.HasOne("CerebusBlazorUI.Classes.Places.USState", "USState")
                        .WithMany()
                        .HasForeignKey("USStateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("USState");
                });
#pragma warning restore 612, 618
        }
    }
}
