// <auto-generated />
using System;
using CerebusBlazorUI.Utilities.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CerebusBlazorUI.Migrations
{
    [DbContext(typeof(CerebusContext))]
    [Migration("20260220025527_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CerebusBlazorUI.Classes.Places.USState", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("USStates");
                });

            modelBuilder.Entity("CerebusBlazorUI.Classes.User.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MiddleNameOrInitial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            City = "New York",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Bob.Reed@Cerebus.fake",
                            FirstName = "Bob",
                            HireDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Reed",
                            MiddleNameOrInitial = "L",
                            Password = "AHDy/36nvmOIZZ+86saNDDFVoWZqPdMNLScwq3GykJc7AdtNYTTHXzchpD1KiIYQCQ==",
                            PhoneNumber = "646-555-3047",
                            State = "32",
                            StreetAddress = "814 Geraldine Lane",
                            Title = "CEO",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Bob.Reed",
                            ZipCode = "10011"
                        },
                        new
                        {
                            ID = 2,
                            City = "Buffalo",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Latoya.Carter@Cerebus.fake",
                            FirstName = "Latoya",
                            HireDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Carter",
                            MiddleNameOrInitial = "N",
                            Password = "ANAQW4iT7s3qS+WVncAjgo2la5Zl6EzwzRq2+SSITTQ0nUfilTUofxltn3FDAvoS2w==",
                            PhoneNumber = "716-555-3630",
                            State = "32",
                            StreetAddress = "2034 Jarvis Street",
                            Title = "HR Generalist",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Latoya.Carter",
                            ZipCode = "14222"
                        },
                        new
                        {
                            ID = 3,
                            City = "Cambridge",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2021, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Joshua.Boyer@Cerebus.fake",
                            FirstName = "Joshua",
                            HireDate = new DateTime(2021, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Boyer",
                            MiddleNameOrInitial = "O",
                            Password = "AFI2Nd6dJGY0lKl0gJiBstFZBaUcxaubVUYRtwKKARvO1jfOpNLgHXm6C4qupJE1RA==",
                            PhoneNumber = "508-555-2320",
                            State = "21",
                            StreetAddress = "3821 Randolph Street",
                            Title = "IT Director",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2021, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Joshua.Boyer",
                            ZipCode = "02141"
                        },
                        new
                        {
                            ID = 4,
                            City = "New York",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Sandy.William@Cerebus.fake",
                            FirstName = "Sandy",
                            HireDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "William",
                            MiddleNameOrInitial = "E",
                            Password = "AFo2tWOviyiD7tNSlTU6UNvyrUd6TZ2M5ukl09kV9ZQlr+u5Es8SQSsrw/U1Qr045w==",
                            PhoneNumber = "212-555-3480",
                            State = "32",
                            StreetAddress = "35 Godfrey Road",
                            Title = "Systems Administrator",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Sandy.William",
                            ZipCode = "10022"
                        },
                        new
                        {
                            ID = 5,
                            City = "Hartford",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Christopher.Cross@Cerebus.fake",
                            FirstName = "Christopher",
                            HireDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Cross",
                            MiddleNameOrInitial = "U",
                            Password = "ABuDZTAUpBfjClDnBbuTqsO2Ohw3wZnl6eY2Uhk8Ftxgb1PnxEBj2C+27yaFhDYIYQ==",
                            PhoneNumber = "860-555-0200",
                            State = "7",
                            StreetAddress = "459 Hart Street",
                            Title = "IT Technician",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Christopher.Cross",
                            ZipCode = "06103"
                        },
                        new
                        {
                            ID = 6,
                            City = "Albany",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Trevor.Ryan@Cerebus.fake",
                            FirstName = "Trevor",
                            HireDate = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Ryan",
                            MiddleNameOrInitial = "M",
                            Password = "ABtVwICrTLu8knP/WNfm7usNsC7VExgFjDM6ojcDf0/hOzg+mDF5m8d9tXebXdeedg==",
                            PhoneNumber = "518-555-2034",
                            State = "32",
                            StreetAddress = "3564 Hardesty Street",
                            Title = "IT Technician",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Trevor.Ryan",
                            ZipCode = "12207"
                        },
                        new
                        {
                            ID = 7,
                            City = "Andover",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Arlene.Dawson@Cerebus.fake",
                            FirstName = "Arlene",
                            HireDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Dawson",
                            MiddleNameOrInitial = "R",
                            Password = "ADQ9bxzIYuZeQLSJ5x69PiEYOoIsAOAC8sUM0tMj6eY3BVRE3VTNhzXfFto1mZT1kA==",
                            PhoneNumber = "207-555-2113",
                            State = "19",
                            StreetAddress = "262 Victoria Court",
                            Title = "Software Developer",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Arlene.Dawson",
                            ZipCode = "04216"
                        },
                        new
                        {
                            ID = 8,
                            City = "Clarion",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Anna.Hartman@Cerebus.fake",
                            FirstName = "Anna",
                            HireDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Hartman",
                            MiddleNameOrInitial = "A",
                            Password = "APtnb0sr2RybmObY29ntYRk2frFJPhuyySDWoPeuu/Mgu7SzaFvW/cgs5rrGC0T9PQ==",
                            PhoneNumber = "814-555-1968",
                            State = "38",
                            StreetAddress = "2797 Coal Street",
                            Title = "Customer Service Manager",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Anna.Hartman",
                            ZipCode = "16214"
                        },
                        new
                        {
                            ID = 9,
                            City = "Millington",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Janette.James@Cerebus.fake",
                            FirstName = "Janette",
                            HireDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "James",
                            MiddleNameOrInitial = "W",
                            Password = "ADVBZqOGXLWjgWiQWJR0ZRWnae4cjVGUw4gjiUs+e95eHHplxfQpohqBPZflleZjLw==",
                            PhoneNumber = "908-555-4192",
                            State = "30",
                            StreetAddress = "1198 Hedge Street",
                            Title = "Customer Service Representative",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Janette.James",
                            ZipCode = "07946"
                        },
                        new
                        {
                            ID = 10,
                            City = "Syracuse",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Van.Harmon@Cerebus.fake",
                            FirstName = "Van",
                            HireDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Harmon",
                            MiddleNameOrInitial = "T",
                            Password = "AKy6UXrnR3wdQ5PqaRb+i8HjNdFAragkOvsiARH436549gWB+buaIrv5H9dW1ymgiQ==",
                            PhoneNumber = "315-555-7346",
                            State = "32",
                            StreetAddress = "1698 Saint Marys Avenue",
                            Title = "Customer Service Representative",
                            UpdatedBy = "admin",
                            UpdatedDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "Van.Harmon",
                            ZipCode = "13221"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
